### ISSUE TITLE
cli: fix output stream in docker runner when tty is enabled

### ISSUE THREAD

**Issue by JayjeetAtGithub** [getpopper/popper#804]
Use a config file, say `conf.yml` with the contents similar to the one shown below to reproduce the issue.
```yaml
engine:
  name: docker
  options:
    tty: True
```
