### ISSUE TITLE
cli: add support for workflow-wide image

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#835]
allow using the same image for the entire workflow. For example:

```yaml
uses: docker://ubuntu:18.04

steps:
- id: one
  args: [ls, -la]
- id: two
  args: [echo, hello]
```
