### ISSUE TITLE
q: how to include an env variable that a docker image expects?

### ISSUE THREAD

**Issue by barbaraDorame** [getpopper/popper#844]
I wanted to use this [actions](https://github.com/ivotron/bin/tree/master/filter), but it seems like it relies on the GITHUB_REF env variable, which seems to be set when running github actions. Would be posible to have this be set when running on Popper?

**Comment by ivotron** [comment]
you can either use `env` (see [syntax here](https://popper.readthedocs.io/en/latest/sections/cn_workflows.html#syntax)), or you can do something like:

```yaml
- uses: docker://docker:19.03.3
  secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
  runs: ['/bin/sh']
  args:
  - -c
  - |
    # only push from master branch
    if [[ $GIT_BRANCH == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker push myrepo/myimage:atag
    fi
```
