### ISSUE TITLE
cli: add 'dir' attribute for steps

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#847]
allow a step to specify the working dir where it should run. For example:

```yaml
steps:

- uses: docker://alpine:3.11
  dir: /etc/
  args: ['pwd']
```

and the above should show `/etc` instead of the default which is `/workspace`.

Three things that need to be done:
  * [ ] the [YAML spec](https://github.com/getpopper/popper/blob/master/cli/popper/parser.py#L24) needs to be updated so a new `dir` attribute is valid
  * [ ] a new test for this can be added in the [`cli/test/test_parser.py`](https://github.com/getpopper/popper/blob/master/cli/test/test_parser.py).
  * [ ] document this feature in the [Workflow Syntax](https://github.com/getpopper/popper/blob/master/docs/sections/cn_workflows.md#syntax) and the [CLI Features](https://github.com/getpopper/popper/blob/master/docs/sections/cli_features.md) sections.

**Comment by RicardoHE97** [comment]
Can I do this issue?

**Comment by ivotron** [comment]
Please go ahead! Let us know if you have any questions

**Comment by RicardoHE97** [comment]
Hi @ivotron, I already submitted a PR #853 but I should point out that I found an problem in my implementation to solve this issue. 

If I define `dir` as `/etc/` and if the container uses a curl, this will throw the following error

```
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
```
**How to recreate this error**
Using the following workflow will trigger this error
```yaml
steps:
- id: download CSV file with data on global CO2 emissions
  uses: docker://byrnedo/alpine-curl:0.1.8
  args: [-LO, https://github.com/datasets/co2-fossil-global/raw/master/global.csv]
  dir: /tmp/
```

**Expected result**
A clean download of the csv file that has the url that was passed in the arguments for the step.


Where I could trace this error comes from is from the file `runner_host.py` in the function `run` from the DockerRunner class. 

I have some idea why this is happening but I don't know for sure and I couldn't be able to fix it.
