### ISSUE TITLE
cli: popper sh fails on mac 

### ISSUE THREAD

**Issue by JayjeetAtGithub** [getpopper/popper#850]
# Steps to reproduce

1. Take a workflow like the one shown below in a `.popper.yml` file,
```
steps:
- id: one
  uses: popperized/bin/sh@master
  args: ['sleep', '1000']
```
2. Now, on doing
```
$ popper sh one
```

the execution stalls from the point the container starts, without showing a prompt or having any response to input.

# Expected Behaviour

A bash shell should open in the container interactively.

# Environment

1. Docker version 19.03.8, build afacb8b
2. MacOS Mojave 10.14.6
