### ISSUE TITLE
cli: secrets not available in containers while running popper installed by the installation script

### ISSUE THREAD

**Issue by JayjeetAtGithub** [getpopper/popper#856]
## How to reproduce?

1. Install `popper` using the installation script
2. Take a workflow (`wf.yml`) like the one shown below,
```
steps:
- uses: "popperized/bin/sh@master"
  args: ["echo $NAME"]
  secrets: ["NAME"]

- uses: "docker://alpine:3.11"
  args: ["ls"]
```
As the workflow requires a secret `NAME` to be defined in the current shell, define it by doing,
```
$ export NAME=xxx
```
3. Now, try running the workflow
```
$ popper run -f wf.yml
```
It would be found that although the NAME environment variable is defined in the current shell, popper does not detect it and prompts the user to enter the value of the secret which should not happen. Maybe this is because currently, the `docker run` command in the executable script does not bind the environment variables from the current shell.
