### ISSUE TITLE
cli: include version in `popper ci` command

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#864]
currently, the `popper ci` command generates configuration files for CI services. In that configuration file (for each distinct CI service), Popper adds a command to clone the Popper repository in order to install popper in the CI server before executing a workflow (e.g. [see here for Travis](https://github.com/getpopper/popper/blob/0f0913a/src/popper/commands/cmd_ci.py#L8-L21)). For this issue we will modify the code so that it the `git clone` command now passes the `--branch` flag that will point to the version of Popper being used to generate the file (obtained by parsing the output of the `popper version` command). So for Travis, it will look like:

```yaml
dist: xenial
language: python
python: 3.7
services: docker
install:
- git clone --branch {popper_version}  --depth=1 https://github.com/systemslab/popper /tmp/popper
#           ^^^^^^^^^^^^^^^^^^^^^^^^
- export PYTHONUNBUFFERED=1
- pip install /tmp/popper/cli
script: popper run -f {}
```

We will add the flag as shown above (pointed to by `^^^`). We need to do this for all other services, and add a new `test_cmd_ci.py` file (in the [`src/test/`](https://github.com/getpopper/popper/tree/master/src/test) folder) that ensures that the `popper ci` command works as expected.
