### ISSUE TITLE
cli: engine-agnostic way of building images

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#907]
Proposal to add an `image` attribute for steps that can be used  instead of the `uses` one, with the following:

```yaml
- image:
    name: myregistry.io/myorg/myrepo
    tags:
    - tag1
    - tag2
    dockerfile: path/to/dockerfile/Dockerfile.foo
    context: ./
    build_args:
      ARG1: v14.2.9
      ARG2: another arg
# other step attributes as usual
  runs: [cmd]
  args: [--as, --usual]
```

The above is inspired on docker-compose's syntax. The goal is to have an engine-independent way of specifying how to build images.
