### ISSUE TITLE
cli: allow slurm runner to process 'options' from step's attributes

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#920]
this would be similar to #876 but for slurm. For example:

```yaml
- id: run-training
  uses: docker://gw000/keras
  args: ["./scripts/run_training.sh"]
  options:
    nodes: 2
    cpus-per-task: 2
```

And the above would allow users skip providing a config file:

```bash
popper run -f wf.yml -r slurm -e singularity
```
