### ISSUE TITLE
Substitutions not substituted everywhere

### ISSUE THREAD

**Issue by bertbesser** [getpopper/popper#965]
My goal is to use a substitutions for environment variables and labels, like e.g.
```
steps:
  - id: some-id
    uses: some-image
    env:
      SAMPLE_ENV_VAR: $_POPPER_SUBST_ENV_VAR
    options:
      labels:
        sample-label: $_POPPER_SUBST_LABEL
    args: some-args
```
However, popper does substitutions only within top-level keys of each step (e.g. id), but not within nested keys.

# Observed behavior
`popper run -f the-above-wf.yml --substitution _POPPER_SUBST_ENV_VAR=this-should-appear --substitution _POPPER_SUBST_LABEL=this-should-appear-also` results in
```
steps:
  - id: some-id
    uses: some-image
    env:
      SAMPLE_ENV_VAR: $_POPPER_SUBST_ENV_VAR
    options:
      labels:
        sample-label: $_POPPER_SUBST_LABEL
    args: some-args
```
instead of the expected output.

# Expected behavior
```
steps:
  - id: some-id
    uses: some-image
    env:
      SAMPLE_ENV_VAR: this-should-appear
    options:
      labels:
        sample-label: this-should-appear-also
    args: some-args
```
